service: aws-clojure-simple-http-endpoint

provider:
  name: aws
  runtime: java8
  stage: dev
  region: eu-central-1

package:
  artifact: target/uberjar/nonogram-0.1.0-SNAPSHOT-standalone.jar

functions:
  random-nonogram:
    handler: aws.handler::handleRequest
    memorySize: 256
    events:
      - http:
          path: ping
          method: get
